[server]
headless = true
enableCORS = false
enableXsrfProtection = false
runOnSave = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FF1801"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[logger]
level = "info"
